Structure changes
frequenz-floss/pylint-datetime pull request #16
Opened 2023-07-28 09:16 UTC by jh2007github

Hopefully the requested changes to the structure were performed correctly

2023-07-28 09:27 UTC, jh2007github commented
There are three commits because I worked on top of the first two, because they haven't been merged yet

2023-07-31 07:46 UTC, llucax requested changes
Oh, it seems we can't just ship one module and mark it as typed. It seems like [the only way to specify that a single module is typed is by just putting it into a package](https://github.com/python/typing/issues/1333#issuecomment-1376532053), so it seems we need the directory and a `__init__.py` after all.

I would also split this `Structure changes to repo` into 3 commits:

1. Only formatting changes.
2. Removal of files that shouldn't be stored in the repo
3. Fixing `tests/test_pylint_datetime.py` (ideally removing the tests for `delete_me` instead of adding the `delete_me` function

I would also rebase this on the current `v0.x.x` so it is the first PR we merge, so the other PRs don't have garbage on them (updating binary files that shouldn't be there).

2023-07-31 07:46 UTC, llucax commented on src/py.typed
So this should be `src/pylint_datetime/py.typed`.

2023-07-31 07:46 UTC, llucax commented on src/datetime_time_checker.py
So this should be `src/pylint_datetime/__init__.py`.

2023-07-31 07:46 UTC, llucax commented on tests/test_pylint_datetime.py
> +    return True
Can you just remove all the code from this file, or maybe just leaving an empty test as a place holder?

2023-07-31 10:13 UTC, llucax approved these changes, later dismissed

2023-07-31 10:22 UTC, llucax approved these changes

2023-07-31 10:28 UTC, merged